### ISSUE TITLE
Admin SPA

### ISSUE THREAD

**Issue by Ks89** [Ks89/My-MEAN-website-client#114]
- [ ] Admin - collapse sidebar when resizing #28

- [ ] Admin - Fix navigation problem because the entrypoint is /admin.html #17 

- [ ] Admin unit testing #22 

- [ ] Admin e2e testing #23 

- [ ] Admin - remove @output eventemitter #28

**Comment by Ks89** [comment]
merged all admin issues into a single one
